using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using System.Text.Json;
using TuvInspection.Contracts.Certificates;

namespace TuvInspection.Infrastructure.Certificates;

/// <summary>
/// Renders an inspection certificate as a PDF in the Annex-1 / TÜV Rheinland Arabia style.
/// QuestPDF is community-licensed for non-commercial use; the API caller will configure the
/// commercial license once TÜV procures one.
/// </summary>
public sealed class CertificatePdfRenderer
{
    static CertificatePdfRenderer()
    {
        QuestPDF.Settings.License = LicenseType.Community;
    }

    public byte[] Render(CertificateDetailDto cert)
    {
        return Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(28);
                page.PageColor(Colors.White);
                page.DefaultTextStyle(t => t.FontSize(9).FontColor("#0f172a"));

                page.Header().Element(c => Header(c, cert));
                page.Content().Element(c => Body(c, cert));
                page.Footer().AlignCenter().Text(t =>
                {
                    t.Span("Generated by TÜV Rheinland Arabia Inspection System  ·  ").FontSize(8).FontColor("#64748b");
                    t.Span(cert.CertificateNo).Bold().FontSize(8);
                });
            });
        }).GeneratePdf();
    }

    private static void Header(IContainer container, CertificateDetailDto cert)
    {
        container.Column(col =>
        {
            col.Item().Row(row =>
            {
                row.RelativeItem().Column(c =>
                {
                    c.Item().Text("TÜV Rheinland Arabia LLC").FontSize(14).Bold().FontColor("#0a3d62");
                    c.Item().Text("Inspection Certificate of Thorough Examination").FontSize(10).FontColor("#475569");
                });
                row.ConstantItem(180).AlignRight().Column(c =>
                {
                    c.Item().Text(cert.CertificateNo).FontSize(13).Bold().FontColor("#f97316");
                    c.Item().AlignRight().Text(t =>
                    {
                        t.Span("Issued ").FontColor("#64748b");
                        t.Span(cert.ReportIssueDate.ToString("dd MMM yyyy")).Bold();
                    });
                });
            });
            col.Item().PaddingTop(8).LineHorizontal(1).LineColor("#e5e9f2");
        });
    }

    private static void Body(IContainer container, CertificateDetailDto cert)
    {
        container.PaddingVertical(10).Column(col =>
        {
            // Identification block
            col.Item().PaddingBottom(10).Element(box => InfoBlock(box, "Identification", new[]
            {
                ("Client",              cert.ClientName),
                ("Equipment ID",        cert.EquipmentIdNo),
                ("Equipment type",      cert.EquipmentTypeName),
                ("Inspection type",     InspectionTypeLabel(cert.InspectionType)),
                ("Inspection date",     cert.InspectionDate.ToString("dd MMM yyyy")),
                ("Next inspection due", cert.NextDueDate?.ToString("dd MMM yyyy") ?? "—"),
                ("Load test",           LoadTestLabel(cert.LoadTest)),
                ("Sticker no.",         cert.StickerNo ?? "—"),
            }));

            col.Item().PaddingBottom(10).Element(box => InfoBlock(box, "Reference standards", new[]
            {
                ("Standards", cert.Standards ?? "—"),
                ("Lifecycle state", cert.State.ToString()),
                ("Result", InspectionResultLabel(cert.Result)),
            }));

            // Checklist
            var items = ParseChecklist(cert.ChecklistJson);
            if (items.Count > 0)
            {
                col.Item().PaddingTop(6).Text("Inspection checklist").FontSize(11).Bold().FontColor("#0f172a");
                col.Item().PaddingTop(4).Element(box => ChecklistTable(box, items));
            }

            // Transitions
            if (cert.Transitions.Count > 0)
            {
                col.Item().PaddingTop(14).Text("Lifecycle history").FontSize(11).Bold().FontColor("#0f172a");
                col.Item().PaddingTop(4).Element(box => HistoryTable(box, cert));
            }

            // Sign-off
            var sigs = ParseSignatures(cert.SignaturesJson);
            col.Item().PaddingTop(20).Element(box => SignOff(box, sigs));
        });
    }

    private static void InfoBlock(IContainer container, string title, IReadOnlyList<(string Label, string Value)> rows)
    {
        container.Column(col =>
        {
            col.Item().Text(title).FontSize(10).Bold().FontColor("#0f172a");
            col.Item().PaddingTop(2).Background("#f8fafc").Padding(8).Border(0.5f).BorderColor("#e5e9f2").Table(t =>
            {
                t.ColumnsDefinition(c => { c.RelativeColumn(1); c.RelativeColumn(2); c.RelativeColumn(1); c.RelativeColumn(2); });
                for (int i = 0; i < rows.Count; i += 2)
                {
                    var left = rows[i];
                    var right = i + 1 < rows.Count ? rows[i + 1] : (Label: "", Value: "");
                    t.Cell().Text(left.Label).FontSize(8).FontColor("#64748b");
                    t.Cell().Text(left.Value).Bold();
                    t.Cell().Text(right.Label).FontSize(8).FontColor("#64748b");
                    t.Cell().Text(right.Value).Bold();
                }
            });
        });
    }

    private static List<ChecklistItem> ParseChecklist(string? json)
    {
        if (string.IsNullOrWhiteSpace(json)) return new();
        try
        {
            var doc = JsonSerializer.Deserialize<ChecklistDoc>(json,
                new JsonSerializerOptions { PropertyNameCaseInsensitive = true });
            return doc?.Items ?? new();
        }
        catch { return new(); }
    }

    private static void ChecklistTable(IContainer container, IReadOnlyList<ChecklistItem> items)
    {
        container.Border(0.5f).BorderColor("#e5e9f2").Table(t =>
        {
            t.ColumnsDefinition(c =>
            {
                c.ConstantColumn(28);
                c.RelativeColumn(4);
                c.RelativeColumn(2);
                c.ConstantColumn(50);
                c.RelativeColumn(3);
            });

            t.Header(h =>
            {
                h.Cell().Background("#f1f5f9").Padding(4).Text("#").Bold().FontSize(8);
                h.Cell().Background("#f1f5f9").Padding(4).Text("Acceptance criteria").Bold().FontSize(8);
                h.Cell().Background("#f1f5f9").Padding(4).Text("Reference").Bold().FontSize(8);
                h.Cell().Background("#f1f5f9").Padding(4).Text("Result").Bold().FontSize(8);
                h.Cell().Background("#f1f5f9").Padding(4).Text("Remark").Bold().FontSize(8);
            });

            foreach (var i in items)
            {
                t.Cell().Padding(3).Text(i.ItemNo).FontSize(8);
                t.Cell().Padding(3).Text(i.AcceptanceCriteria).FontSize(8);
                t.Cell().Padding(3).Text(i.ReferenceStandard).FontSize(8);
                t.Cell().Padding(3).Background(ResultColor(i.Result))
                    .AlignCenter().Text(i.Result == "NotSet" ? "—" : i.Result).Bold().FontSize(8);
                t.Cell().Padding(3).Text(i.Remark).FontSize(8);
            }
        });
    }

    private static string ResultColor(string result) => result switch
    {
        "Pass" => "#dcfce7",
        "Fail" => "#fee2e2",
        "NA"   => "#f1f5f9",
        _      => "#ffffff",
    };

    private static void HistoryTable(IContainer container, CertificateDetailDto cert)
    {
        container.Border(0.5f).BorderColor("#e5e9f2").Table(t =>
        {
            t.ColumnsDefinition(c =>
            {
                c.RelativeColumn(2);
                c.RelativeColumn(2);
                c.RelativeColumn(1);
                c.RelativeColumn(3);
            });

            t.Header(h =>
            {
                h.Cell().Background("#f1f5f9").Padding(4).Text("From → To").Bold().FontSize(8);
                h.Cell().Background("#f1f5f9").Padding(4).Text("When (UTC)").Bold().FontSize(8);
                h.Cell().Background("#f1f5f9").Padding(4).Text("Actor role").Bold().FontSize(8);
                h.Cell().Background("#f1f5f9").Padding(4).Text("Comments").Bold().FontSize(8);
            });

            foreach (var tr in cert.Transitions.OrderBy(t => t.AtUtc))
            {
                t.Cell().Padding(3).Text($"{tr.FromState} → {tr.ToState}").FontSize(8);
                t.Cell().Padding(3).Text(tr.AtUtc.ToString("dd MMM yyyy HH:mm")).FontSize(8);
                t.Cell().Padding(3).Text(tr.ActorRole).FontSize(8);
                t.Cell().Padding(3).Text(tr.Comments ?? "—").FontSize(8);
            }
        });
    }

    private static void SignOff(IContainer container, IReadOnlyList<SignatureEntry> sigs)
    {
        var slots = new[] { "Inspector", "Reviewed by (TÜV)", "Receiver (Client)" };
        container.Row(row =>
        {
            for (int i = 0; i < slots.Length; i++)
            {
                if (i > 0) row.ConstantItem(20);
                var label = slots[i];
                var sig = sigs.FirstOrDefault(s =>
                    string.Equals(s.Role, label, StringComparison.OrdinalIgnoreCase) ||
                    LabelMatches(s.Role, label));
                row.RelativeItem().Column(c =>
                {
                    c.Item().Text(label).FontSize(8).FontColor("#64748b");
                    if (sig is not null && TryDecodeImage(sig.DataUrl, out var bytes))
                    {
                        c.Item().PaddingTop(4).Height(48).Image(bytes).FitArea();
                        c.Item().PaddingTop(2).LineHorizontal(0.5f).LineColor("#94a3b8");
                        c.Item().PaddingTop(2).Text(text =>
                        {
                            text.Span(string.IsNullOrWhiteSpace(sig.Name) ? "Signed" : sig.Name).Bold().FontSize(8);
                            if (sig.AtUtc is { } at)
                            {
                                text.Span("  ·  ").FontColor("#94a3b8").FontSize(8);
                                text.Span(at.ToString("dd MMM yyyy HH:mm")).FontSize(8).FontColor("#64748b");
                            }
                        });
                    }
                    else
                    {
                        c.Item().PaddingTop(28).LineHorizontal(0.5f).LineColor("#94a3b8");
                        c.Item().PaddingTop(2).Text("Signature / Date").FontSize(8).FontColor("#94a3b8");
                    }
                });
            }
        });
    }

    private static bool LabelMatches(string role, string label)
    {
        if (string.IsNullOrWhiteSpace(role)) return false;
        var r = role.Replace(" ", "").ToLowerInvariant();
        return label switch
        {
            "Inspector" => r.Contains("inspector"),
            "Reviewed by (TÜV)" => r.Contains("review") || r.Contains("tuv") || r.Contains("tüv") || r.Contains("approver") || r.Contains("manager"),
            "Receiver (Client)" => r.Contains("client") || r.Contains("receiver") || r.Contains("customer"),
            _ => false,
        };
    }

    private static bool TryDecodeImage(string? dataUrl, out byte[] bytes)
    {
        bytes = Array.Empty<byte>();
        if (string.IsNullOrWhiteSpace(dataUrl)) return false;
        var idx = dataUrl.IndexOf("base64,", StringComparison.OrdinalIgnoreCase);
        var payload = idx >= 0 ? dataUrl[(idx + 7)..] : dataUrl;
        try { bytes = Convert.FromBase64String(payload); return bytes.Length > 0; }
        catch { return false; }
    }

    private static IReadOnlyList<SignatureEntry> ParseSignatures(string? json)
    {
        if (string.IsNullOrWhiteSpace(json)) return Array.Empty<SignatureEntry>();
        try
        {
            var arr = JsonSerializer.Deserialize<List<SignatureEntry>>(json,
                new JsonSerializerOptions { PropertyNameCaseInsensitive = true });
            return arr ?? new();
        }
        catch { return Array.Empty<SignatureEntry>(); }
    }

    private sealed class SignatureEntry
    {
        public string Role { get; set; } = "";
        public string? Name { get; set; }
        public string? DataUrl { get; set; }
        public DateTime? AtUtc { get; set; }
    }

    // ----- enums to labels -----
    private static string InspectionTypeLabel(CertificateInspectionTypeDto t) => t switch
    {
        CertificateInspectionTypeDto.PeriodicInspection => "Periodic (P.I.)",
        CertificateInspectionTypeDto.ReInspection       => "Re-inspection (Re.I.)",
        CertificateInspectionTypeDto.InitialInspection  => "Initial (I.I.)",
        _ => t.ToString(),
    };

    private static string LoadTestLabel(LoadTestKindDto t) => t switch
    {
        LoadTestKindDto.None       => "—",
        LoadTestKindDto.Mechanical => "Mechanical (M)",
        LoadTestKindDto.Witnessed  => "Witnessed (W)",
        LoadTestKindDto.Performed  => "Performed (P)",
        _ => t.ToString(),
    };

    private static string InspectionResultLabel(InspectionResultDto r) => r switch
    {
        InspectionResultDto.Pass                 => "Pass",
        InspectionResultDto.Fail                 => "Fail",
        InspectionResultDto.FailWithObservations => "Fail with observations",
        _ => "Not set",
    };

    private sealed class ChecklistDoc
    {
        public List<ChecklistItem> Items { get; set; } = new();
    }
    private sealed class ChecklistItem
    {
        public string ItemNo { get; set; } = "";
        public string AcceptanceCriteria { get; set; } = "";
        public string ReferenceStandard { get; set; } = "";
        public string Result { get; set; } = "NotSet";
        public string Remark { get; set; } = "";
    }
}
